main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace = 'user')),
    path('', include('review.urls', namespace = 'review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'review'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('post/', views.PostMovieView.as_view(), name = 'post'),
    path('movielist/', views.MovieListView.as_view(), name = 'movieList'),
    path('<uuid:pk>/manage/', views.ManageMovie.as_view(), name = 'manage'),
    path('<uuid:pk>/post/comment/', views.PostCommentView.as_view(), name = 'postComment'),
    path('<uuid:pk>/update/comment/', views.UpdateCommentView.as_view(), name = 'updateComment'),
    path('<uuid:pk>/delete/comment/', views.DeleteCommentView.as_view(), name = 'deleteComment'),
    path('<uuid:id>/like/', views.CommentLikeToggleView.as_view(), name = 'commentLike'),
    path('<uuid:id>/dislike/', views.CommentDislikeToggleView.as_view(), name = 'commentDislike'),
    path('<uuid:id>/report/', views.CommentReportToggleView.as_view(), name = 'commentReport'),
    path('<uuid:pk>/rate/', views.PostRatingView.as_view(), name = 'postRating'),
    path('<int:pk>/update/rating/', views.UpdateRatingView.as_view(), name = 'updateRating'),
    path('movie/search', views.SearchView.as_view(), name = 'search'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('pass-reset/', auth_views.PasswordResetView.as_view(
            template_name = 'registration/password_reset.html',
            success_url = reverse_lazy('user:password_reset_done'),
            html_email_template_name = 'registration/password_reset_email.html'
            ), name = 'password_rest'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_success.html'), name='password_reset_done'),
    path('pass-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url = reverse_lazy('user:password_reset_complete')
            ), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('uploads/', views.UserMovieList.as_view(), name = 'userUploads'),
    path('notactivated/', TemplateView.as_view(template_name = 'user/not_activated.html'), name = 'accountNotActivated'),
    path('<slug:username>/subscribers/', views.SubscriberListView.as_view(), name ='subscriberList'),
    path('<uuid:pk>/confirm/', views.ConfirmView.as_view(), name = 'confirmUser'),
    path('<slug:username>/notify/', views.NotifyToggleView.as_view(), name = 'notify'),
    path('image/update/', views.UserDpUpdateView.as_view(), name = 'updateProfileImage'),
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name = 'profile'),
    path('<int:pk>/seen/', views.MessageSeenRedirectView.as_view(), name = 'seen'),
    path('profile/<slug:username>/update/', views.UserProfileUpdateView.as_view(), name = "updateProfile"),
]

review/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from uuid import uuid4
from PIL import Image
from django.contrib import messages

import logging

logger =  logging.getLogger('django.request')


class MovieManager(models.Manager):
    def get_rating_range(self):
        return range(self.ratting)


class Movie(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    name = models.CharField(max_length = 240)
    poster = models.ImageField(upload_to = 'posters')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    ratting = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk' : self.id})

    def __str__(self):
        return f'{self.name}'

    def as_elasticsearch_dict(self):
        return {
            '_id' : self.id,
            '_type' : 'doc',
            'text' : '{} \n {}'.format(self.name, self.description),
            'movie_description' : self.description,
            'name' : self.name,
            'id' : self.id,
            'created' : self.date,
            'username' : self.user.username,
            'poster_url' : self.poster.url,
            'rating' : self.ratting,
        }

    def save(self, force_insert = False, force_update = False, using = None, update_fields = None):
        is_new = self._state.adding or force_insert
        super().save(force_insert = False, force_update = False, using = None, update_fields = None)

        img = Image.open(self.poster.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.poster.path)

        if is_new:
            self.create_message()
    
    def create_message(self):
        from user.models import Message
        Message.objects.create(user = self.user, message = f'{self.user} added a new movie review {self.name}', movie = self)



class Comment(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_likes', blank = True)
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_dislikes', blank = True)
    reports = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_reports', blank = True)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})

    def __str__(self):
        return f'{self.user} commented on {self.movie}'

class RatingManager(models.Manager):
    def get_rating_or_unsaved_rating(self, movie, user):
        try:
            return Ratting.objects.get(
                movie = movie,
                user = user
            )
        except Ratting.DoesNotExist:
            return Ratting(
                movie = movie,
                user = user,
            )

class Ratting(models.Model):
    choices = (
        (1, "💥"),
        (2, "💥💥"),
        (3, "💥💥💥"),
        (4, "💥💥💥💥"),
        (5, "💥💥💥💥💥"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE, related_name = 'user_rating')
    ratted = models.IntegerField(default = 0, choices= choices)

    objects = RatingManager()

    class Meta:
        unique_together = ('user', 'movie')

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})
    
    def __str__(self):
        return '{} ratted {}'.format(self.movie, self.ratted)
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.user == self.movie.user:
            logger.error("you're the author so cannot rate on the movie")
        else:
            return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

review/forms.py
from django import forms
from . models import Movie, Comment, Ratting
from django.contrib.auth import get_user_model
from . get_ratings import GetRatings
from django.shortcuts import HttpResponseRedirect 

class PostMovieForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True
    )

    class Meta:
        model = Movie
        fields = ['user', 'name', 'poster', 'description']
        widgets = {
            'name' : forms.TextInput(attrs = {'autofocus' : True}),
            'poster': forms.FileInput(attrs = {'onchange': "previewFile()"})
        }

class CommentForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True
    )
    movie = forms.ModelChoiceField(
        queryset = Movie.objects.all(),
        disabled = True,
        widget = forms.HiddenInput,
    )

    class Meta:
        model = Comment
        fields = ['user', 'movie', 'comment']

class RattingForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True,
    )
    movie = forms.ModelChoiceField(
        queryset = Movie.objects.all(),
        disabled = True,
        widget = forms.HiddenInput,
    )

    class Meta:
        model = Ratting
        fields = ['user', 'movie', 'ratted']

review/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView, RedirectView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . forms import PostMovieForm, CommentForm, RattingForm
from django.contrib.messages.views import SuccessMessageMixin
from . models import Movie, Ratting, Comment
from . import mixins


class PostMovieView(LoginRequiredMixin, mixins.PostMovieMixin, CreateView):
    form_class = PostMovieForm
    template_name = 'review/post_movie.html'
    success_message = 'Successfully posted the movie.'

class ManageMovie(LoginRequiredMixin, mixins.ManageMovieMixin, DetailView):
    model = Movie

class MovieListView(ListView):
    model = Movie
    ordering = ['-date']
    paginate_by = 10

# Comment block

class PostCommentView(LoginRequiredMixin, mixins.UpdateCreateCommentMixin, CreateView):
    form_class = CommentForm
    template_name = 'review/create_comment.html'
    success_message = "You have posted a comment!"
    update = False

class UpdateCommentView(mixins.UpdateCreateCommentMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'review/comment_update_form.html'
    success_message = 'Your Comment has been updated!'
    update = True

class CommentLikeToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'like'

class CommentDislikeToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'dislike'

class CommentReportToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'report'

class DeleteCommentView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        obj = self.get_object()
        url = obj.movie.get_absolute_url()
        return url

# Rating block

class PostRatingView(LoginRequiredMixin, mixins.PostRatingMixin, CreateView):
    form_class = RattingForm
    success_message = "Thanks for your valuable rating"
    update = False

class UpdateRatingView(LoginRequiredMixin, mixins.PostRatingMixin, UpdateView):
    model = Ratting
    form_class = RattingForm
    success_message = "Your Ratting has been updated"
    update = True

# Search

class SearchView(mixins.SearchViewMixin, TemplateView):
    template_name = 'review/search.html' 

# About

class AboutView(TemplateView):
    template_name = 'review/about.html'

review/templates/review/about.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }} - About
{% endblock title %}
{% block body %}
<h3>This is a web page created to write your review about a movie. Other users can rate your movieReview and show their
    response by commenting your review
</h3>
{% endblock body %}

review/templates/review/comment_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}
{% endblock title %}
{% block body %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the comment</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'review:manage' object.movie.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock body %}

review/templates/review/comment_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - UpdateComment
{% endblock title %}
{% block body %}
<form action="" method="post" class="col-md-8">
    {% csrf_token %}
    {{ form | crispy}}
    <button type="submit" class="btn btn-success">Update</button>
</form>
{% block script %}
<script>
    window.onload = function() {
        document.getElementsByTagName("textarea")[0].focus();
    };
</script>
{% endblock script %}
{% endblock body %}

review/templates/review/create_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Post comment
{% endblock title %}
{% block body %}
<div class="col-md-12">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock body %}

review/templates/review/movie_detail.html
{% extends 'base.html' %}
{% block title %}
{{ object }} - Manage
{% endblock title %}
{% block body %}
{% include 'common/detail.html' %}
{% if object.comment_set.all %}
{% include 'common/comment_list.html' %}
{% endif %}
{% include 'common/post_comment.html' %}
{% endblock body %}

review/templates/review/movie_list.html
{% extends 'base.html' %}
{% block title %}
Movie List
{% endblock title %}
{% block body %}
<h1>Read and Write Your Thoughts:</h1>
{% for movie in movie_list %}
{% include 'common/detail.html' with object=movie list_view=True %}
{% empty %}
<h2>There is no movie to show!!!!</h2>
{% endfor %}
{% block pagination %}
{{ block.super }}
{% endblock pagination %}
{% endblock body %}

review/templates/review/post_movie.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Post a Movie
{% endblock title %}
{% block body %}

<h1>Post the leatest Movie</h1>
<hr class="wave">

{% if preview %}
<div class="box preview-box">
    <h3>Preview:</h3>
    {% include 'common/detail.html' with object=preview %}
</div>
{% endif %}

{% if preview %}
<div class="box preview-box">
    <h3>Edit Here:</h3>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data" class="my-ajax-form col-sm-12 col-md-9"
        data-url=" {{ request.build_absolute_uri | safe }} ">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" name="action" value="preview" class="btn btn-success">Preview</button>
        <button type="submit" name="action" value="save" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock body %}
{% block script %}
<script>
    function previewFile() {
        var preview = document.querySelector('img');
        var file = document.querySelector('input[type=file]').files[0];
        var reader = new FileReader();

        reader.onloadend = function () {
            preview.src = reader.result;
        }

        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
</script>
{% endblock script %}

review/templates/review/search.html
{% extends 'base.html' %}
{% load markdownify %}
{% load filters %}
{% block title %}
Search
{% endblock title %}
{% block body %}
<h2>Search</h2>
<form action="" method="get" class="form-inline">
    <input type="search" name="q" id="" class="form-control mr-2" value="{{ query }}">
    <button type="submit" class="btn btn-primary">Search</button>
</form>
{% if query %}
<h3>Result from search query '{{ query }}' </h3>
<ul class="list-unstyled search-results">
    {% for hit in hits %}
    <div class="row detail box preview-box detail-box">
        <div class="col-md-3">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 rounded">
                    <img src="{{ hit.poster_url }}" alt="Movie Poster">
                    <p><b>Written by:</b> <a href="{% url 'user:profile' username=hit.username %}"> {% if user.username == hit.username %} You {% else %} {{ hit.username }} {% endif %}</a></p>
                </div>
                <br>
            </div>
        </div>

        <div class="col-sm-9 col-md-9 col-lg-9">
            <h2><a href="{% url 'review:manage' pk=hit.id %}">{{hit.name}}</a>
                <div class="rating">
                    <span class="badge badge-success">
                        {% for i in hit.rating|times %}
                        {% if i == 0 %}
                        Rated:
                        {% endif %}
                        <span>☆</span>
                        {% empty %}
                        Start Rating
                        {% endfor %}
                    </span>
                </div></h2>
            <hr>
            <p class="box">
                {{ hit.movie_description | markdownify}}</p>
        </div>
    </div>
    {% empty %}
    <li>No results.</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock body %}

review/templates/review/test.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
    <div class="col-sm-12">
    <form id="ratingForm" method="POST">
    <div class="form-group">
    <h4>Rate this product</h4>
    <button type="button" class="btn btn-warning btn-sm rateButton" aria-label="Left Align">
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-default btn-grey btn-sm rateButton" aria-label="Left Align">
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-default btn-grey btn-sm rateButton" aria-label="Left Align">
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-default btn-grey btn-sm rateButton" aria-label="Left Align">
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </button>
    <button type="button" class="btn btn-default btn-grey btn-sm rateButton" aria-label="Left Align">
    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    </button>
    <input type="hidden" class="form-control" id="rating" name="rating" value="1">
    <input type="hidden" class="form-control" id="itemId" name="itemId" value="12345678">
    </div>
    <div class="form-group">
    <label for="usr">Title*</label>
    <input type="text" class="form-control" id="title" name="title" required>
    </div>
    <div class="form-group">
    <label for="comment">Comment*</label>
    <textarea class="form-control" rows="5" id="comment" name="comment" required></textarea>
    </div>
    <div class="form-group">
    <button type="submit" class="btn btn-info" id="saveReview">Save Review</button> <button type="button" class="btn btn-info" id="cancelReview">Cancel</button>
    </div>
    </form>
    </div>
    </div>
{% endblock body %}