main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace = 'user')),
    path('', include('review.urls', namespace = 'review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'review'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('post/', views.PostMovieView.as_view(), name = 'post'),
    path('movielist/', views.MovieListView.as_view(), name = 'movieList'),
    path('<uuid:pk>/manage/', views.ManageMovie.as_view(), name = 'manage'),
    path('<uuid:pk>/post/comment/', views.PostCommentView.as_view(), name = 'postComment'),
    path('<uuid:pk>/update/comment/', views.UpdateCommentView.as_view(), name = 'updateComment'),
    path('<uuid:pk>/delete/comment/', views.DeleteCommentView.as_view(), name = 'deleteComment'),
    path('<uuid:id>/like/', views.CommentLikeToggleView.as_view(), name = 'commentLike'),
    path('<uuid:id>/dislike/', views.CommentDislikeToggleView.as_view(), name = 'commentDislike'),
    path('<uuid:id>/report/', views.CommentReportToggleView.as_view(), name = 'commentReport'),
    path('<uuid:pk>/rate/', views.PostRatingView.as_view(), name = 'postRating'),
    path('<int:pk>/update/rating/', views.UpdateRatingView.as_view(), name = 'updateRating'),
    path('movie/search', views.SearchView.as_view(), name = 'search'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('pass-reset/', auth_views.PasswordResetView.as_view(
            template_name = 'registration/password_reset.html',
            success_url = reverse_lazy('user:password_reset_done'),
            html_email_template_name = 'registration/password_reset_email.html'
            ), name = 'password_rest'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_success.html'), name='password_reset_done'),
    path('pass-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url = reverse_lazy('user:password_reset_complete')
            ), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('uploads/', views.UserMovieList.as_view(), name = 'userUploads'),
    path('notactivated/', TemplateView.as_view(template_name = 'user/not_activated.html'), name = 'accountNotActivated'),
    path('<slug:username>/subscribers/', views.SubscriberListView.as_view(), name ='subscriberList'),
    path('<uuid:pk>/confirm/', views.ConfirmView.as_view(), name = 'confirmUser'),
    path('<slug:username>/notify/', views.NotifyToggleView.as_view(), name = 'notify'),
    path('image/update/', views.UserDpUpdateView.as_view(), name = 'updateProfileImage'),
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name = 'profile'),
    path('<int:pk>/seen/', views.MessageSeenRedirectView.as_view(), name = 'seen'),
    path('profile/<slug:username>/update/', views.UserProfileUpdateView.as_view(), name = "updateProfile"),
]

review/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from uuid import uuid4
from PIL import Image
from django.contrib import messages

import logging

logger =  logging.getLogger('django.request')


class MovieManager(models.Manager):
    def get_rating_range(self):
        return range(self.ratting)


class Movie(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    name = models.CharField(max_length = 240)
    poster = models.ImageField(upload_to = 'posters')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    ratting = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk' : self.id})

    def __str__(self):
        return f'{self.name}'

    def as_elasticsearch_dict(self):
        return {
            '_id' : self.id,
            '_type' : 'doc',
            'text' : '{} \n {}'.format(self.name, self.description),
            'movie_description' : self.description,
            'name' : self.name,
            'id' : self.id,
            'created' : self.date,
            'username' : self.user.username,
            'poster_url' : self.poster.url,
            'rating' : self.ratting,
        }

    def save(self, force_insert = False, force_update = False, using = None, update_fields = None):
        is_new = self._state.adding or force_insert
        super().save(force_insert = False, force_update = False, using = None, update_fields = None)

        img = Image.open(self.poster.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.poster.path)

        if is_new:
            self.create_message()
    
    def create_message(self):
        from user.models import Message
        Message.objects.create(user = self.user, message = f'{self.user} added a new movie review {self.name}', movie = self)



class Comment(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_likes', blank = True)
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_dislikes', blank = True)
    reports = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_reports', blank = True)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})

    def __str__(self):
        return f'{self.user} commented on {self.movie}'

class RatingManager(models.Manager):
    def get_rating_or_unsaved_rating(self, movie, user):
        try:
            return Ratting.objects.get(
                movie = movie,
                user = user
            )
        except Ratting.DoesNotExist:
            return Ratting(
                movie = movie,
                user = user,
            )

class Ratting(models.Model):
    choices = (
        (1, "💥"),
        (2, "💥💥"),
        (3, "💥💥💥"),
        (4, "💥💥💥💥"),
        (5, "💥💥💥💥💥"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE, related_name = 'user_rating')
    ratted = models.IntegerField(default = 0, choices= choices)

    objects = RatingManager()

    class Meta:
        unique_together = ('user', 'movie')

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})
    
    def __str__(self):
        return '{} ratted {}'.format(self.movie, self.ratted)
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.user == self.movie.user:
            logger.error("you're the author so cannot rate on the movie")
        else:
            return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

review/forms.py
from django import forms
from . models import Movie, Comment, Ratting
from django.contrib.auth import get_user_model
from . get_ratings import GetRatings
from django.shortcuts import HttpResponseRedirect 

class PostMovieForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True
    )

    class Meta:
        model = Movie
        fields = ['user', 'name', 'poster', 'description']
        widgets = {
            'name' : forms.TextInput(attrs = {'autofocus' : True}),
            'poster': forms.FileInput(attrs = {'onchange': "previewFile()"})
        }

class CommentForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True
    )
    movie = forms.ModelChoiceField(
        queryset = Movie.objects.all(),
        disabled = True,
        widget = forms.HiddenInput,
    )

    class Meta:
        model = Comment
        fields = ['user', 'movie', 'comment']

class RattingForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset = get_user_model().objects.all(),
        widget = forms.HiddenInput,
        disabled = True,
    )
    movie = forms.ModelChoiceField(
        queryset = Movie.objects.all(),
        disabled = True,
        widget = forms.HiddenInput,
    )

    class Meta:
        model = Ratting
        fields = ['user', 'movie', 'ratted']

review/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView, RedirectView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . forms import PostMovieForm, CommentForm, RattingForm
from django.contrib.messages.views import SuccessMessageMixin
from . models import Movie, Ratting, Comment
from . import mixins


class PostMovieView(LoginRequiredMixin, mixins.PostMovieMixin, CreateView):
    form_class = PostMovieForm
    template_name = 'review/post_movie.html'
    success_message = 'Successfully posted the movie.'

class ManageMovie(LoginRequiredMixin, mixins.ManageMovieMixin, DetailView):
    model = Movie

class MovieListView(ListView):
    model = Movie
    ordering = ['-date']
    paginate_by = 10

# Comment block

class PostCommentView(LoginRequiredMixin, mixins.UpdateCreateCommentMixin, CreateView):
    form_class = CommentForm
    template_name = 'review/create_comment.html'
    success_message = "You have posted a comment!"
    update = False

class UpdateCommentView(mixins.UpdateCreateCommentMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'review/comment_update_form.html'
    success_message = 'Your Comment has been updated!'
    update = True

class CommentLikeToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'like'

class CommentDislikeToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'dislike'

class CommentReportToggleView(mixins.CommentActionMixin, RedirectView):
    model = Comment
    choice = 'report'

class DeleteCommentView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        obj = self.get_object()
        url = obj.movie.get_absolute_url()
        return url

# Rating block

class PostRatingView(LoginRequiredMixin, mixins.PostRatingMixin, CreateView):
    form_class = RattingForm
    success_message = "Thanks for your valuable rating"
    update = False

class UpdateRatingView(LoginRequiredMixin, mixins.PostRatingMixin, UpdateView):
    model = Ratting
    form_class = RattingForm
    success_message = "Your Ratting has been updated"
    update = True

# Search

class SearchView(mixins.SearchViewMixin, TemplateView):
    template_name = 'review/search.html' 

# About

class AboutView(TemplateView):
    template_name = 'review/about.html'

review/templates/common/comment_list.html
{% load markdownify %}

<h2>Comments</h2>
<div class="row">
    {% for comment in object.comment_set.all %}
    <div class="col-md-4 box user-box">
        <div class="div box preview-box">
            {% if comment.user.profile %}
            <img src=" {{comment.user.profile.img.url}} " alt="" class="rounded profile-pic">
            {% else %}
            <img src=" {{object.poster.url}} " alt="" class="rounded profile-pic">
            {% endif %}
            <a href="{% url 'user:profile' comment.user.username %}"> {{ comment.user }} </a>
            <small>posted on: {{ comment.date }} </small>
            <div style="display: flex; justify-content: space-evenly;">
                <a href="{% url 'review:commentLike' id=comment.id %}" class="btn btn-like" name="action" value="like">
                    👍
                    <p><small> {{ comment.likes.count }} </small></p>
                </a>
                <a href="{% url 'review:commentDislike' id=comment.id %}" class="btn btn-like" name="action"
                    value="like">
                    👎
                    <p><small> {{ comment.dislikes.count }} </small></p>
                </a>
                <a href="{% url 'review:commentReport' id=comment.id %}" class="btn btn-like" name="action"
                    value="report">
                    Report
                    <p><small> {{ comment.reports.count }} </small></p>
                </a>
                {% if user == comment.user %}
                <div style="display: flex; flex-direction: column;">
                    <small>
                        <a class="btn btn-small btn-update"
                            href="{% url 'review:updateComment' pk=comment.id %}">Update</a>
                    </small>
                    <small>
                        <a href="{% url 'review:deleteComment' pk=comment.id %}" type="submit"
                            class="btn btn-small btn-delete">Delete</a>

                    </small>
                </div>
                {% endif %}
            </div>
        </div>

    </div>
    <div class="col-md-8 box comment-box">

        {{ comment.comment | markdownify}}
    </div>
    {% endfor %}
</div>

review/templates/common/detail.html
{% load filters %}
{% load markdownify %}
{% load crispy_forms_tags %}
{% if preview %}
<div class="alert alert-warning">
    To View the poster just choose the file agian.I know it is a bug but soon will fix it. Sorry of the inconvenience!!
</div>
{% endif %}
<div class="row detail box preview-box detail-box">
    <div class="col-md-3">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 rounded">
                {% if preview %}
                <img src="" alt="Poster">
                {% else %}
                <img src=" {% if object.poster %}{{ object.poster.url }}{% endif %} " alt="Movie Poster">
                {% endif %}
            </div>
            <br>
            <div class="col-sm-12 col-md-12 col-lg-12 rounded">
                <b> Written by: </b>
                {% if user %}
                {% if user.username == object.user.username %}
                <a href="{% url 'user:profile' username=object.user.username %}">You</a>
                {% else %}
                <a href="{% url 'user:profile' username=object.user.username %}">{{ object.user.username }}</a>
                {% endif %}
                {% else %}
                <a href="{% url 'user:profile' username=object.user.username %}">{{ object.user.username }}</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm-9 col-md-9 col-lg-9">
        {% if list_view %}
        <h2> <a href=" {% url 'review:manage' pk=object.id %} ">{{object.name}}</a>
            <div class="rating">
                <span class="badge badge-success">
                    {% for i in object.ratting|times %}
                    {% if i == 0 %}
                    Rated:
                    {% endif %}
                    <span>☆</span>
                    {% empty %}
                    Start Rating
                    {% endfor %}
                </span>
            </div>
        </h2>
        {% else %}
        <h2>{{object.name}}
            <div class="rating">
                <span class="badge badge-success">
                    {% for i in object.ratting|times %}
                    {% if i == 0 %}
                    Rated:
                    {% endif %}
                    <span>☆</span>
                    {% empty %}
                    Start Rating
                    {% endfor %}
                </span>
            </div>
        </h2>
        {% endif %}
        <hr>
        <p class="box">
            {{ object.description | markdownify}}
            {% if not list_view %}
            {% if user.is_authenticated %}
            {% if not rated %}
            <p><b class="alert alert-warning">You have not rated this moive!</b></p>
            {% endif %}
            <form method="post" action="{{ rating_form_url }}">
                {% csrf_token %}
                {{ rating_form | crispy}}
                <button type="submit" class="btn btn-primary">Rate</button>
            </form>
            {% endif %}
            {% endif %}
    </div>
</div>

review/templates/common/post_comment.html
{% load crispy_forms_tags %}
<h2>Post Your comment:</h2>
<div class="row box preview-box">
    <div class="col-md-9">
        <form action="{% url 'review:postComment' pk=object.id  %}" method="post">
            {% csrf_token %}
            {{ comment_form | crispy}}
            <button type="submit" class="btn btn-primary" name="action" value="save">Submit</button>
        </form>
    </div>
</div>