main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace = 'user')),
    path('', include('review.urls', namespace = 'review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'review'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('post/', views.PostMovieView.as_view(), name = 'post'),
    path('movielist/', views.MovieListView.as_view(), name = 'movieList'),
    path('<uuid:pk>/manage/', views.ManageMovie.as_view(), name = 'manage'),
    path('<uuid:pk>/post/comment/', views.PostCommentView.as_view(), name = 'postComment'),
    path('<uuid:pk>/update/comment/', views.UpdateCommentView.as_view(), name = 'updateComment'),
    path('<uuid:pk>/delete/comment/', views.DeleteCommentView.as_view(), name = 'deleteComment'),
    path('<uuid:id>/like/', views.CommentLikeToggleView.as_view(), name = 'commentLike'),
    path('<uuid:id>/dislike/', views.CommentDislikeToggleView.as_view(), name = 'commentDislike'),
    path('<uuid:id>/report/', views.CommentReportToggleView.as_view(), name = 'commentReport'),
    path('<uuid:pk>/rate/', views.PostRatingView.as_view(), name = 'postRating'),
    path('<int:pk>/update/rating/', views.UpdateRatingView.as_view(), name = 'updateRating'),
    path('movie/search', views.SearchView.as_view(), name = 'search'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('pass-reset/', auth_views.PasswordResetView.as_view(
            template_name = 'registration/password_reset.html',
            success_url = reverse_lazy('user:password_reset_done'),
            html_email_template_name = 'registration/password_reset_email.html'
            ), name = 'password_rest'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_success.html'), name='password_reset_done'),
    path('pass-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url = reverse_lazy('user:password_reset_complete')
            ), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('uploads/', views.UserMovieList.as_view(), name = 'userUploads'),
    path('notactivated/', TemplateView.as_view(template_name = 'user/not_activated.html'), name = 'accountNotActivated'),
    path('<slug:username>/subscribers/', views.SubscriberListView.as_view(), name ='subscriberList'),
    path('<uuid:pk>/confirm/', views.ConfirmView.as_view(), name = 'confirmUser'),
    path('<slug:username>/notify/', views.NotifyToggleView.as_view(), name = 'notify'),
    path('image/update/', views.UserDpUpdateView.as_view(), name = 'updateProfileImage'),
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name = 'profile'),
    path('<int:pk>/seen/', views.MessageSeenRedirectView.as_view(), name = 'seen'),
    path('profile/<slug:username>/update/', views.UserProfileUpdateView.as_view(), name = "updateProfile"),
]

review/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from uuid import uuid4
from PIL import Image
from django.contrib import messages

import logging

logger =  logging.getLogger('django.request')


class MovieManager(models.Manager):
    def get_rating_range(self):
        return range(self.ratting)


class Movie(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    name = models.CharField(max_length = 240)
    poster = models.ImageField(upload_to = 'posters')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    ratting = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk' : self.id})

    def __str__(self):
        return f'{self.name}'

    def as_elasticsearch_dict(self):
        return {
            '_id' : self.id,
            '_type' : 'doc',
            'text' : '{} \n {}'.format(self.name, self.description),
            'movie_description' : self.description,
            'name' : self.name,
            'id' : self.id,
            'created' : self.date,
            'username' : self.user.username,
            'poster_url' : self.poster.url,
            'rating' : self.ratting,
        }

    def save(self, force_insert = False, force_update = False, using = None, update_fields = None):
        is_new = self._state.adding or force_insert
        super().save(force_insert = False, force_update = False, using = None, update_fields = None)

        img = Image.open(self.poster.path)

        if img.height > 300 and img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.poster.path)

        if is_new:
            self.create_message()
    
    def create_message(self):
        from user.models import Message
        Message.objects.create(user = self.user, message = f'{self.user} added a new movie review {self.name}', movie = self)



class Comment(models.Model):
    id = models.UUIDField(primary_key = True, default = uuid4, editable = False)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_likes', blank = True)
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_dislikes', blank = True)
    reports = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'comment_reports', blank = True)

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})

    def __str__(self):
        return f'{self.user} commented on {self.movie}'

class RatingManager(models.Manager):
    def get_rating_or_unsaved_rating(self, movie, user):
        try:
            return Ratting.objects.get(
                movie = movie,
                user = user
            )
        except Ratting.DoesNotExist:
            return Ratting(
                movie = movie,
                user = user,
            )

class Ratting(models.Model):
    choices = (
        (1, "💥"),
        (2, "💥💥"),
        (3, "💥💥💥"),
        (4, "💥💥💥💥"),
        (5, "💥💥💥💥💥"),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE, related_name = 'user_rating')
    ratted = models.IntegerField(default = 0, choices= choices)

    objects = RatingManager()

    class Meta:
        unique_together = ('user', 'movie')

    def get_absolute_url(self):
        return reverse('review:manage', kwargs = {'pk': self.movie.id})
    
    def __str__(self):
        return '{} ratted {}'.format(self.movie, self.ratted)
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.user == self.movie.user:
            logger.error("you're the author so cannot rate on the movie")
        else:
            return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from uuid import uuid4
from review.models import Movie
from . import tasks

class Profile(models.Model):
    idConform = models.UUIDField(default = uuid4, editable = False)
    img = models.ImageField(default = 'img.jpg', upload_to = 'profile_pic')
    user = models.OneToOneField(User, on_delete = models.CASCADE, blank = True)
    confirmed = models.BooleanField(default = False)
    notify = models.ManyToManyField(User, related_name = 'notifies', blank = True)
    email_send = False

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.img.path)
        if img.height > 300 and img.width > 300:
            img.thumbnail((300, 300))
            img.save(self.img.path)

class Message(models.Model):
    message = models.CharField(max_length = 200)
    user = models.ForeignKey(to=User, on_delete = models.CASCADE)
    movie = models.ForeignKey(to = Movie, on_delete = models.CASCADE)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        is_new = self._state.adding or force_insert
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        
        if is_new:
            tasks.make_subscriber_messages.delay(self.id)

class SubscriberMessageManager(models.Manager):
    def create_from_message(self, message):
        subscribers = message.user.profile.notify.all()
        return [
            self.create(message = message, subscriber = subscriber)
            for subscriber in subscribers
        ]


class SubscriberMessage(models.Model):
    message = models.ForeignKey(to = Message, on_delete = models.CASCADE)
    subscriber = models.ForeignKey(to = User, on_delete = models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)
    send = models.DateTimeField(default = None, null = True)
    last_attempt = models.DateTimeField(default = None, null = True)
    seen = models.BooleanField(default = False)

    objects = SubscriberMessageManager()

    def __str__(self):
        return '{} message from {}'.format(self.subscriber, self.message.user)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from . models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(u'Email addresses must be unique.!')
        return email
    
    def save(self, *args, **kwargs):
        email = self.clean_email()
        super().save(*args, **kwargs)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2',]

class UpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = get_user_model()
        fields = ['email', 'username']

class UserProfileForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset= get_user_model().objects.all(),
        disabled = True,
        widget = forms.HiddenInput
    )

    class Meta:
        model = Profile
        fields = ['img', 'user']
        widgets = {
            'img': forms.FileInput(attrs = {'onchange': "upload()"})
        }

user/views.py
from . import mixins
from . models import Profile
from django.views import generic
from . forms import UserRegisterForm
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

class LoginView(auth_views.LoginView):
    def get_success_url(self):
        return reverse('user:profile', kwargs = { 'username' : self.request.user.username})

class RegisterView(mixins.RegisterViewMixin, generic.CreateView):
    template_name = 'user/register.html'
    form_class = UserRegisterForm

class ConfirmView(mixins.ConfirmViewMixin, generic.DetailView):
    model = Profile
    template_name = 'user/confirm_user_view.html'

class NotifyToggleView(LoginRequiredMixin,mixins.NotifyToggleViewMixin, generic.RedirectView):
    notify_toggle_view = True

class UserProfileView(LoginRequiredMixin, mixins.UserProfileViewMixin, generic.DetailView):
    model = User
    template_name = 'user/user_detail.html'

class UserMovieList(LoginRequiredMixin, mixins.UserMovieListMixin, generic.ListView):
    template_name = 'user/user_movie_list.html'
    ordering = ['-date']
    paginate_by = 10

class UserProfileUpdateView(LoginRequiredMixin, mixins.UserProfileUpdateViewMixin, generic.TemplateView):
    template_name = "user/profile_update.html"

class UserDpUpdateView(mixins.UserDpUpdateViewMixin, generic.RedirectView):
    user_dp_update = True

class MessageSeenRedirectView(mixins.MessageSeenRedirectViewMixin, generic.RedirectView):
    message_seen_view = True

class SubscriberListView(LoginRequiredMixin, mixins.SubscriberListViewMixin, generic.ListView):
    model = User
    paginate_by = 10
    template_name = 'user/subscriber_list.html'

user/templates/user/confirm_user_view.html
{% extends 'base.html' %}
{% block title %}
Confirmation Page
{% endblock title %}
{% block body %}
<h1>Your account has been activated</h1>
{% endblock body %}

user/templates/user/not_activated.html
{% extends 'base.html' %}
{% block title %}
Not Activated
{% endblock title %}
{% block body %}
<h1>Your account is not Activated!!</h1>
<hr>
<p>To post Movies you need to activate your account</p>
<p>Check your email for activation message</p>
{% endblock body %}

user/templates/user/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Update Your profile
{% endblock title %}
{% block body %}
<h1>Update Your Profile:</h1>
<form method="POST" enctype="multipart/form-data" class = 'col-md-7'>
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Update</button>
    </div>
</form>
{% endblock body %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
SignUp
{% endblock title %}
{% block body %}
<div class="col-md-6 col-sm-12 center box preview-box radius">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy}}
        <button type="submit" class="btn btn-primary">SignUp</button>
    </form>
</div>
{% endblock body %}

user/templates/user/subscriber_list.html
{% extends 'base.html' %}
{% block title %}
Subscriber List
{% endblock title %}
{% block body %}
<div class="row">
    {% for subscriber in object_list %}
    <div class="col-md-12 box preview-box">
        <div class="row">
            <div class="user-image col-md-3 box preview-box" style="margin-left: 10px; text-align: center;">
                <div class="rounded" style="text-align: center;">
                    <img src="{{ subscriber.profile.img.url }}" alt="User dp">
                </div>
            </div>
            <div class="col-md-8">
                <div class="user-details box preview-box">
                    <div class="box user-name" style="display: flex; justify-content: space-between;">
                        <div>
                            <b>User Name: </b>{{ subscriber.username }}
                        </div>
                    </div>
                    <p> <b>Email: </b>{{ subscriber.email }} </p>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <h2 style="color: darkred">No subscribers yet</h2>
    {% endfor %}
</div>
{% block pagination %}
{{ block.super }}
{% endblock pagination %}
{% endblock body %}

user/templates/user/user_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load markdownify %}
{% block title %}
Profile
{% endblock title %}
{% block body %}
<div class="row">
    <div class="user-image col-md-3 col-sm-4 box preview-box">
        <div class="rounded">
            {% if user == current_user %}
            {% if user.profile.img == 'img.jpg' %}
            <p style="font-weight: bold;">Upload an Image:</p>
            <form id='myForm' enctype="multipart/form-data" action="{% url 'user:updateProfileImage' %}" method="post"
                class="box" style="margin-bottom: 5px;">
                {# for field in p_form #}
                {% if field.errors %}
                <ul>
                    {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% csrf_token %}
                {{ field }}
                {# endfor #}
                {% csrf_token %}
                {{ p_form }}
            </form>
            {% endif %}
            {% endif %}
            <img src=" {{ object.profile.img.url }} " alt="Profile pic">
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div class="row" style="margin-left: auto;">
            <div class="col-md-12">
                <div class="user-details box preview-box">
                    <div class="box user-name" style="display: flex; justify-content: space-between;">
                        <div>
                            <b>User Name: </b>{{ object.username }}
                        </div>
                        <div class=" " style="padding: 0;">
                            {% if current_user == user %}
                            <small><b><a href="{{ url }}" class="btn btn-outline-danger"> Edit </a></b></small>
                            {% endif %}
                        </div>
                    </div>
                    <p> <b>Email: </b>{{ user.email }} </p>
                </div>
            </div>
        </div>
        <div class="col-md-12 user-action">
            {% if current_user == user %}
            <a href="{% url 'review:post' %}" class="btn btn-primary">Post a Movie Review</a>
            <a href="{% url 'user:subscriberList' username=current_user.username %}" class="btn btn-danger">Subscribers {{ current_user.profile.notify.count }}</a>
            {% else %}
            <a href="{% url 'user:notify' username=user.username %}"
                class="btn btn-{% if subscribe %}success{% else %}danger{% endif %} subscribe">
                {% if not subscribe %}
                <span class="notify" onmouseover="show_notify()" onmouseout="hide_notify()">
                    Notify
                    <span style="color: blanchedalmond; font-weight: bold;">
                        {% if user.profile.notify.count %}
                        {{ user.profile.notify.count }}
                        {% endif %}
                    </span>
                    {% else %}
                    <span>
                        Subscribed
                        {% if user.profile.notify.count %}
                        {{ user.profile.notify.count }}
                        {% endif %}
                    </span>
                </span>
                {% endif %}
            </a>
            <span class="notify-help">Subscribe to his reviews</span>
            {% endif %}
        </div>
    </div>
</div>
</div>
<hr>
<div class="row">
    <div class="col-md-3" style="margin-left: auto;">
        <h2>Your Reviews:</h2>
    </div>
    <div class="col-md-8" style="margin-right: auto;">
        <div class="box preview-box">
            {% if user.movie_set %}
            {% for movie in user.movie_set.all %}
            {% include 'common/detail.html' with object=movie list_view=True %}
            {% empty %}
            <h2>You don't have uploaded any!</h2>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% if current_user %}
    <button id="message" onclick="toggleMessage()">Messages</button>
    <div class="message-popup" id='popup-message'>
        {% for message in user_messages %}
        <div class="message-widget">
            <div class="h4">
                <h4>{{ message.message.user }}'s new Review</h4>
                <hr>
            </div>
            <div class="body">
                <b>Movie:</b> {{ message.message.movie.name|truncatewords_html:10 }}
                <p>
                    <a href="{% url 'user:seen' pk=message.id %}"
                        class="btn btn-{% if message.seen %}primary{% else %}success{% endif %}">
                        {% if message.seen %}Seen{% else %}See{% endif %}
                    </a>
                </p>
            </div>
        </div>
        {% empty %}
        <p>Is empty</p>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% block script %}
<script>

    function toggleMessage() {
        popup_message = document.getElementById('popup-message').style.display;
        if (popup_message == '' || popup_message == 'none') {
            document.getElementById('popup-message').style.display = 'block';
        } else {
            document.getElementById('popup-message').style.display = 'none';
        }
    }

    function upload() {
        var reader = new FileReader();
        var file = document.querySelector('input[type=file]').files[0];
        reader.onloadend = function () {
            document.getElementById('myForm').submit();
        }
        if (file)
            reader.readAsDataURL(file);
    }

    function show_notify() {
        ele = document.getElementsByClassName('notify-help')[0].style.visibility = 'visible';
    }

    function hide_notify() {
        ele = document.getElementsByClassName('notify-help')[0].style.visibility = 'hidden';
    }

</script>
{% endblock script %}
{% endblock body %}

user/templates/user/user_movie_list.html
{% extends 'base.html' %}
{% block title %}
{{ user }} Reviews
{% endblock title %}
{% block body %}
<h1>Movie Reviews Written by {{ user.username }}: </h1>
<hr>
{% for object in movie_list %}
{% include 'common/detail.html' with object=object list_view=True %}
{% empty %}
<h2 style="color: chocolate;">No Reviews written:</h2>
{% endfor %}
{% block pagination %}
{{ block.super }}
{% endblock pagination %}
{% endblock body %}