main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace = 'user')),
    path('', include('review.urls', namespace = 'review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'review'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('post/', views.PostMovieView.as_view(), name = 'post'),
    path('movielist/', views.MovieListView.as_view(), name = 'movieList'),
    path('<uuid:pk>/manage/', views.ManageMovie.as_view(), name = 'manage'),
    path('<uuid:pk>/post/comment/', views.PostCommentView.as_view(), name = 'postComment'),
    path('<uuid:pk>/update/comment/', views.UpdateCommentView.as_view(), name = 'updateComment'),
    path('<uuid:pk>/delete/comment/', views.DeleteCommentView.as_view(), name = 'deleteComment'),
    path('<uuid:id>/like/', views.CommentLikeToggleView.as_view(), name = 'commentLike'),
    path('<uuid:id>/dislike/', views.CommentDislikeToggleView.as_view(), name = 'commentDislike'),
    path('<uuid:id>/report/', views.CommentReportToggleView.as_view(), name = 'commentReport'),
    path('<uuid:pk>/rate/', views.PostRatingView.as_view(), name = 'postRating'),
    path('<int:pk>/update/rating/', views.UpdateRatingView.as_view(), name = 'updateRating'),
    path('movie/search', views.SearchView.as_view(), name = 'search'),
]

user/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('pass-reset/', auth_views.PasswordResetView.as_view(
            template_name = 'registration/password_reset.html',
            success_url = reverse_lazy('user:password_reset_done'),
            html_email_template_name = 'registration/password_reset_email.html'
            ), name = 'password_rest'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_success.html'), name='password_reset_done'),
    path('pass-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
            success_url = reverse_lazy('user:password_reset_complete')
            ), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('uploads/', views.UserMovieList.as_view(), name = 'userUploads'),
    path('notactivated/', TemplateView.as_view(template_name = 'user/not_activated.html'), name = 'accountNotActivated'),
    path('<slug:username>/subscribers/', views.SubscriberListView.as_view(), name ='subscriberList'),
    path('<uuid:pk>/confirm/', views.ConfirmView.as_view(), name = 'confirmUser'),
    path('<slug:username>/notify/', views.NotifyToggleView.as_view(), name = 'notify'),
    path('image/update/', views.UserDpUpdateView.as_view(), name = 'updateProfileImage'),
    path('profile/<slug:username>/', views.UserProfileView.as_view(), name = 'profile'),
    path('<int:pk>/seen/', views.MessageSeenRedirectView.as_view(), name = 'seen'),
    path('profile/<slug:username>/update/', views.UserProfileUpdateView.as_view(), name = "updateProfile"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} movieReview{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'css/main.css' %} ">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">movie<span class="r">R</span>eview</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">

                        <form action="" method="get" class="form-inline">
                            <input type="search" name="q" id="" class="form-control mr-2" value="{{ query }}">
                            <button type="submit" class="btn btn-primary">Search</button>
                        </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'review:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'review:movieList' %}">MovieList</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        {% if current_user %}
                        <a class="nav-link js-scroll-trigger"
                            href="{% url 'user:profile' username=current_user.username %}">Profile</a>
                        {% else %}
                        <a class="nav-link js-scroll-trigger"
                            href="{% url 'user:profile' username=user.username %}">Profile</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'review:post' %}" class="nav-link js-scroll-trigger">Post</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:login' %}">LogIn</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-custom">

        {% if messages %}
        <div>
            <ul class="ul-messages">
                {% for message in messages %}
                <li class="alert alert-{{message.tags}}"> {{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {% if form_errors %}
        {% for field, errors in form_errors.items %}
        {% for error in errors %}
        <div class="alert alert-danger"> {{ error }}</div>
        {% endfor %}
        {% endfor %}
        {% endif %}

        {% block body %}
        {% block pagination %}
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
        {% endblock pagination %}
        {% endblock body %}
    </div>
    <script src=" {% static '/js/bootstrap.min.js' %} "></script>
    {% block script %}
    {% endblock script %}
</body>

</html>